### ISSUE TITLE
Script fails on first run when using playlist name argument

### ISSUE THREAD

**Issue by sim667** [robobeaver6/plex_playlist_generator#1]
You need to create a dummy playlist with the same name passed via the playlist name argument.

**Comment by robobeaver6** [comment]
Congratulations on raising issue #1  :)

I guess I never noticed this, as it is always replacing an existing one.  Thanks for letting me know, I will look into it

**Comment by robobeaver6** [comment]
It was trying to delete a playlist that wasn't there, so it was throwing an exception.  I have added a handler for it, so that should now be resolved.
