### ISSUE TITLE
Want to mod it a little to have random seasons and episodes.

### ISSUE THREAD

**Issue by mikegamer2064** [robobeaver6/plex_playlist_generator#2]
Hi i love your great generator script
you have done a good job.. 
can you help me...
i want to modify it a little

i am using it to watch my anime in order... thats great

but i got  6 cartoon series including the simpsons(31 seasons1) and i want to play themn ramdomly with your generator..

with plex i alomost listen to the simpsons all the time all the other show wont show...

so help me show me what to modify so i can watch randomly any seasonfor example

simpsons season 5 ep 3
familguy season 10 ep9

...
..
..
..
simpsons season 23 ep21

you see what i mean help me please i tried myself but didnt work..

i tried put some random.randint but still not doing want i want it to do

**Comment by robobeaver6** [comment]
Glad you find it useful.  I don't think you need the generator for doing what you want, as it is achievable in the Plex web app.  Just go to the top level of the Simpsons series, and add  it to a new playlist, then play with shuffle turned on.

**Comment by mikegamer2064** [comment]
no i want to listen to my shows randomly..
when i shuffle all the shows i almost listen to the simpsons because i hav e 31 seasons..
so what can i modify to play  randomly instead of in order.???

ex:

simpsons after that family guy after the american dad etc etc... (random episode and season)

for now it only plays:

simpsons simpsons south park simpsons simpsons simpsons amerciand dad simpsons simpsons....
so i need your script but modified to be random show , seasons ans episodes.. help me please

**Comment by robobeaver6** [comment]
so you want to play an episode from a random show, where each show is weighted equally, regardless of the number of episodes, and you don't want the next unwatched, you want a random unwatched episode.

**Comment by mikegamer2064** [comment]
yes i tried a lot of time modifying the script but cant understand how to do it...

i start the playlist then it will
begin: simpsons or anything....then another show ransom season and episodes...

like simpsons s03e04
american dad s08e02
etc etc ok? it is possible?

**Comment by robobeaver6** [comment]
OK,  pull the latest version.  there are three new flags
--randomize which will shuffle the episodes within a series.
--ignore-skiped which will prevent it from checking if there is a missing episode.
--include-watched which will generate a playlist form all episodes, not just unwatched.  Only makes sense if randomize is also enabled

**Comment by mikegamer2064** [comment]
oh okay its that simple thank you  :)

**Comment by robobeaver6** [comment]
It wasn't,  I changed the code around to add those flags.  I had a logic error,  so pull it again if you have already pulled it

**Comment by mikegamer2064** [comment]
i exececute the script but says error line 6...
i put this:

playlist_generator.py --server --baseurl "http://192.168.1.128:32400" --token "aDBRpoab9zvDG_crzY5i"

i got:

 File "C:\plexscript\playlist_generator.py", line 6
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by robobeaver6** [comment]
in the command you run the script from .  order of arguments doesn't matter
e.g.
```
playlist_generator.py --server --baseurl "http://172.16.1.100:32400" --token "fR5GrDxfLunKynNub5" --randomize
```

**Comment by mikegamer2064** [comment]
there erro in your script:

 File "C:\plexscript\playlist_generator.py", line 6
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by robobeaver6** [comment]
runs fine here.  Have you pulled the latest version?

**Comment by mikegamer2064** [comment]
well i downlaod a fille that make 104 ko instated of 4 ko (the ancient one) is thaT ONE?

**Comment by mikegamer2064** [comment]
i got this on the code... is it normal???
```




<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
```
...Tiedied up to make it readable

**Comment by robobeaver6** [comment]
No.  you downloaded a github web page, not the python code.

**Comment by mikegamer2064** [comment]
ahahagh i was soooooo lost it worked now i copied your code directly and tadaaaa.... thanks a lot  for you help... i thought icould just download it by right click at it....

**Comment by robobeaver6** [comment]
No problem
