### ISSUE TITLE
TVDB now requires an API key

### ISSUE THREAD

**Issue by danielb2** [robobeaver6/plex_playlist_generator#5]
```
Traceback (most recent call last):
  File "/home/daniel/tmp/plex_playlist_generator/playlist_generator.py", line 178, in <module>
    main()
  File "/home/daniel/tmp/plex_playlist_generator/playlist_generator.py", line 162, in main
    episodes = get_random_episodes(all_shows, n=args.number)
  File "/home/daniel/tmp/plex_playlist_generator/playlist_generator.py", line 83, in get_random_episodes
    if skipped_missing(all_shows.get(title=show_name), show_episodes[show_name][0]):
  File "/home/daniel/tmp/plex_playlist_generator/playlist_generator.py", line 122, in skipped_missing
    previous_season_count = tvdb_season_count(show, season_num - 1)
  File "/home/daniel/tmp/plex_playlist_generator/playlist_generator.py", line 100, in tvdb_season_count
    raise RuntimeError(f'TVDB now requires an API key.  Instructions on how to set it up are here:\n\n'
RuntimeError: TVDB now requires an API key.  Instructions on how to set it up are here:

https://koditips.com/create-tvdb-api-key-tv-database/


```

I'm invoking the script via the `--server` method, and according to the help, the `--tvdb-api-key` is only needed for the "Plex Account Connection Method". A miss?

**Comment by GhostGuy9** [comment]
TVDB Started slowly removing the api keys and this error happened to me last night a couple times. It happens to specific shows and removing the show fixes the problem.

**Comment by danielb2** [comment]
Adding the key solved the direct issue for me, but then I got another error for another show for which I had deleted seasons 1 and 2. 

> :__main__:SKIP_CHECK: Previous Episode not Found for <SHOW> S2E1

no idea how to proceed here now, but I didn't say anything originally since it wasn't related to this issue

**Comment by GhostGuy9** [comment]
Thats normal its only checking if it's a valid skip and should output "SKIP_CHECK: Passed" if it succeeded in the skip. I'm not too understanding of the code yet.

**Comment by danielb2** [comment]
Ah, that itself wasn't the problem. I pasted wrong:

```
INFO:__main__:SKIP_CHECK: Previous Episode not Found for <SHOW> S2E1
Traceback (most recent call last):
  File "/home/daniel/tmp/plex_playlist_generator/playlist_generator.py", line 178, in <module>
    main()
  File "/home/daniel/tmp/plex_playlist_generator/playlist_generator.py", line 162, in main
    episodes = get_random_episodes(all_shows, n=args.number)
  File "/home/daniel/tmp/plex_playlist_generator/playlist_generator.py", line 83, in get_random_episodes
    if skipped_missing(all_shows.get(title=show_name), show_episodes[show_name][0]):
  File "/home/daniel/tmp/plex_playlist_generator/playlist_generator.py", line 122, in skipped_missing
    previous_season_count = tvdb_season_count(show, season_num - 1)
  File "/home/daniel/tmp/plex_playlist_generator/playlist_generator.py", line 98, in tvdb_season_count
    tvdb_id = int(re.search('thetvdb://([0-9]+)?', show.guid).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
(
```

**Comment by GhostGuy9** [comment]
Is there any other args you are using besides Debug and TVDB api key? It seems to have a problem with skipping the missing episode and I can re-create it to produce that.

**Comment by rich9474** [comment]
It was a while ago since I wrote this.  I will need to remind myself how it works.  I will try and have a look at the weekend.

**Comment by danielb2** [comment]
`playlist_generator.py --server --token <token> --baseurl <url> --tvdb-api-key <api-key>`

**Comment by GhostGuy9** [comment]
able to replicate the error with one of my shows i have, its oddly just not working period so because this line > `tvdb_id = int(re.search('thetvdb://([0-9]+)?', show.guid).group(1))`
 removing it fixes the problem but not sure how important that line is for the TVDB part of the code.

`tvdb_id = int(re.search('thetvdb://([0-9]+)?', show.guid).group(1))`

**Comment by GhostGuy9** [comment]
Looks like it has something to to with the GUID, if your using Plex's new library agent it will not work and breaks that code for some shows. Using the TVDB agent fixes the problem
